export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored just for you",
        description: "Get interview questions and model answers based on your role, experience, skill level, and specific focus areas - so every practice session is personalized to match your career goals and the kind of interviews you're preparing for."
    },
    {
        id: "02",
        title: "Learn at Your Own Pace",
        description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations, examples, and additional context that help you understand difficult topics without overwhelming you."
    },
    {
        id: "03",
        title: "Capture Your Insights",
        description: "Add personal notes to any question and pin important ones to the top - making your learning more organized and helping you keep track of useful insights, key concepts, and questions you want to revisit before your interview."
    },
    {
        id: "04",
        title: "Understand the 'why' Behind Answers",
        description: "Go beyond memorizing answers and understand the reasoning behind them. Unlock detailed concept explanations generated by AI, helping you connect the dots, strengthen your fundamentals, and confidently explain your answers during the interview."
    },
    {
        id: "05",
        title: "Save, Organize and Revisit",
        description: "Easily save your interview sets, organize them neatly in your dashboard, and revisit them whenever you need. Keep your preparation structured in one place and pick up exactly where you left off as you continue improving your interview skills."
    }
]
